version: "2"
services:
  app:
    image: samldd/my-workforce-frontend
    links:
      - identifier:backend
    ports:
      - 80:80
  identifier:
    image: semtech/mu-identifier:1.0.0
    links:
      - dispatcher:dispatcher
  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    links:
      - resource:resource
      - workforce:workforce
      - generator:generator
    volumes:
      - ./config/dispatcher:/config
  db:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources:1.12.4
    links:
      - db:database
    volumes:
      - ./config/resources:/config
  generator:
    image: samldd/my-workforce-generator
    links:
     - db:database
  workforce:
    image: samldd/my-workforce-backend
    links:
      - db:database
