version: "2"
services:
  identifier:
    image: semtech/mu-identifier:1.0.0
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    links:
      - resource:resource
      - workforce:workforce
      - generator:generator
    volumes:
      - ./config/dispatcher:/config
  db:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources:1.12.4
    links:
      - db:database
    volumes:
      - ./config/resources:/config
    ports:
      - "4567:80" 
  generator:
    image: my-generator
    links:
     - db:database
    environment:
      MODE: "development"
    volumes: 
     - /home/sam/PycharmProjects/my-generator/:/app
  workforce:
    image: my-workforce
    links:
      - db:database
    environment:
      MODE: "development"
    volumes: 
     - /home/sam/PycharmProjects/my-workforce/:/app
